///////////////////////////////////////////////////////////
//  Address.cs
//  Implementation of the Class Address
//  Generated by Enterprise Architect
//  Created on:      04-Apr-2016 6:48:40 PM
//  Original author: ENVY
///////////////////////////////////////////////////////////




public class Address {

	private int apartmentNum;
	private int buildingNum;
	private string city;
	private string street;

	public Address(){

	}

	~Address(){

	}

	public virtual void Dispose(){

	}

	/// 
	/// <param name="street"></param>
	/// <param name="city"></param>
	/// <param name="buildingNum"></param>
	/// <param name="appartmentNum"></param>
	public Address(string street, string city, int buildingNum, int appartmentNum){
        this.street = street;
        this.city = city;
        this.buildingNum = buildingNum;
        this.apartmentNum = appartmentNum;
	}

}//end Address