///////////////////////////////////////////////////////////
//  Complainant.cs
//  Implementation of the Class Complainant
//  Generated by Enterprise Architect
//  Created on:      04-Apr-2016 6:48:41 PM
//  Original author: ENVY
///////////////////////////////////////////////////////////
using System.Collections;
using Db4objects.Db4o;
using System;

public class Complainant {

	private Address address;
	public Name name;
	private ArrayList phoneNumber;
	private int SSN;

    public static IObjectContainer db;
    public static int start = 1; 

    
	public Complainant(){

	}

	~Complainant(){

	}

	public virtual void Dispose(){

	}

	/// 
	/// <param name="SSN"></param>
	/// <param name="phoneNumber"></param>
	/// <param name="name"></param>
	/// <param name="address"></param>
	public Complainant(int SSN, ArrayList phoneNumber, Name name, Address address){
        this.SSN = SSN;
        this.phoneNumber = phoneNumber;
        this.name = name;
        this.address = address;
	}

	/// 
	/// <param name="SSN"></param>
	public string DeleteComplainantData(int SSN){

		return "";
	}


    public void startDatabase()
    {
        if(start==1)
        { 
        db = Db4oFactory.OpenFile("Db.yap");
        start = 0; 
        }
    }
	/// 
	/// <param name="SSN"></param>
	/// <param name="phoneNumber"></param>
	/// <param name="name"></param>
	/// <param name="address"></param>
	public void InsertComplainantData(Complainant comp){
        
        db.Store(comp);
       
	}

	/// 
	/// <param name="SSN"></param>
	public ArrayList RetrieveComplainantData(int SSN){
        //Console.WriteLine(com);
        Complainant compl = new Complainant();
        IObjectSet allcomps= db.QueryByExample(typeof(Complainant));
        for (int i = 0; i < allcomps.Count; i++)
        {
            compl = (Complainant)allcomps[i];
            //ComboBoxName.Items.Add(stu.name);
            //Console.WriteLine();
            if (compl.SSN.Equals(SSN))
            {
                //Name n= new Name();
                Console.WriteLine(compl.SSN);
            }
            
        }

		return null;
	}
	/// 
	/// <param name="SSN"></param>
	public string UpdateComplainantData(int SSN){

		return "";
	}

}//end Complainant