///////////////////////////////////////////////////////////
//  Location.cs
//  Implementation of the Class Location
//  Generated by Enterprise Architect
//  Created on:      04-Apr-2016 6:48:42 PM
//  Original author: ENVY
///////////////////////////////////////////////////////////




public class Location {

	public string region;
	public int XCoordinate;
	public int YCoordinate;
	

	public Location(){

	}

	~Location(){

	}

	public virtual void Dispose(){

	}

	/// 
	/// <param name="YCoordinate"></param>
	/// <param name="XCoordinate"></param>
	/// <param name="region"></param>
	public Location(int YCoordinate, int XCoordinate, string region){
        this.YCoordinate = YCoordinate;
        this.XCoordinate = XCoordinate;
        this.region = region;
	}

}//end Location