///////////////////////////////////////////////////////////
//  Name.cs
//  Implementation of the Class Name
//  Generated by Enterprise Architect
//  Created on:      04-Apr-2016 6:48:43 PM
//  Original author: ENVY
///////////////////////////////////////////////////////////




public class Name {

	public string Fname;
	public string Lname;

	public Name(){

	}

	~Name(){

	}

	public virtual void Dispose(){

	}

	/// 
	/// <param name="Lname"></param>
	/// <param name="Fname"></param>
	public Name(string Lname, string Fname){
        this.Lname = Lname;
        this.Fname = Fname;
	}

}//end Name