///////////////////////////////////////////////////////////
//  Officer.cs
//  Implementation of the Class Officer
//  Generated by Enterprise Architect
//  Created on:      04-Apr-2016 6:48:43 PM
//  Original author: ENVY
///////////////////////////////////////////////////////////
using System.Collections;
using Db4objects.Db4o;
using System;


public class Officer : Police {

	private string stationCode;
    private ArrayList patrol_officer = new ArrayList();
   
    public static ArrayList foundpatrols = new ArrayList();

	public Officer(){

	}

	~Officer(){

	}

	public override void Dispose(){

	}

	/// 
	/// <param name="stationCode"></param>
    public Officer(string stationCode, double salary, int badgeNumber, ArrayList phoneNumber, Name name, int ID, Address address, Shift newshift)
    {
        this.stationCode = stationCode;
        this.salary = salary;
        this.badegNumber = badgeNumber;
        this.phoneNumber = phoneNumber;
        this.name = name;
        this.ID = ID;
        this.address = address;
        this.newShift = newshift;
        //this.patrol_officer = patrol_officer;
	}

	/// 
	/// <param name="ID"></param>
	public string DeleteOfficerData(int ID){

		return "";
	}

	/// 
	/// <param name="stationCode"></param>
    public void InsertOfficerData(Officer officer)
    {

        Complainant.db.Store(officer);
    }

	/// 
	/// <param name="ID"></param>
	public ArrayList[] RetrieveOfficeData(int ID){

		return null;
	}

	/// 
	/// <param name="newIncidnet"></param>
	public void SearchPatrolLocation(Report report){
        foundpatrols.Clear();
        IObjectSet allpatrols =Complainant.db.QueryByExample(typeof(Patrol));
        Patrol newPatrol = new Patrol(); 
        for (int i = 0; i < allpatrols.Count; i++)
        {
            newPatrol = (Patrol)allpatrols[i];
           if (newPatrol.patrolLocation.region.Equals(report.newIncident.incidentLocation.region))
            {
              //  if (0.00 <= report.time && report.time <= 12.00)
                //{
                  //  if (newPatrol.newShift.shiftDescription.Equals("Morning"))
                   // {
                        foundpatrols.Add(newPatrol);
                   // }
                    
                }
                //else 
                //{
                  //  if (newPatrol.newShift.shiftDescription.Equals("Night"))
                    //{
                      //  foundpatrols.Add(newPatrol);
                    //}

                //}
                
            }
        }

    public ArrayList GetAllPatrols()
    {
        return foundpatrols;
    }

	/// 
	/// <param name="ID"></param>
	public string UpdateOfficerData(int ID){

		return "";
	}

}//end Officer