///////////////////////////////////////////////////////////
//  Patrol.cs
//  Implementation of the Class Patrol
//  Generated by Enterprise Architect
//  Created on:      04-Apr-2016 6:48:44 PM
//  Original author: ENVY
///////////////////////////////////////////////////////////
using System.Collections;
using Db4objects.Db4o;
using System;



public class Patrol : Police {

	public Location patrolLocation;
    private ArrayList officer_patrol= new ArrayList();
    public static IObjectContainer db;
	public Patrol(){

	}

	~Patrol(){

	}

	public override void Dispose(){

	}

	/// 
	/// <param name="patrolLocation"></param>
    public Patrol(Location patrolLocation, double salary, int badgeNumber, ArrayList phoneNumber, Name name, int ID, Address address, Shift newshift)
    {
        this.patrolLocation = patrolLocation;
        this.salary = salary;
        this.badegNumber = badgeNumber;
        this.phoneNumber = phoneNumber;
        this.name = name;
        this.ID = ID;
        this.address = address;
        this.newShift = newshift;
	}

	/// 
	/// <param name="ID"></param>
	public string DeletePatrolData(int ID){

		return "";
	}
    public Location GetPatrolLocation()
    {
        return patrolLocation;
    }

	/// 
	/// <param name="patrolLocation"></param>
	public void InsertPatrolData(Patrol patrol){
        Complainant.db.Store(patrol);
    }

	/// 
	/// <param name="ID"></param>
	public ArrayList[] RetrievePatrolData(int ID){

		return null;
	}

	/// 
	/// <param name="ID"></param>
	public string UpdatePatrolData(int ID){

		return "";
	}
}//end Patrol