///////////////////////////////////////////////////////////
//  Report.cs
//  Implementation of the Class Report
//  Generated by Enterprise Architect
//  Created on:      04-Apr-2016 6:48:44 PM
//  Original author: ENVY
///////////////////////////////////////////////////////////
using System.Collections;
using Db4objects.Db4o;


public class Report {

	private string date;
    private int reportID;
    public double time;

	
	public Incident newIncident;
    public Complainant newComplainant;
    private Officer newOfficer= new Officer();


	public Report(){

	}

	~Report(){

	}

	public virtual void Dispose(){

	}

	/// 
	/// <param name="newComplainant"></param>
	/// <param name="newOfficer"></param>
	/// <param name="newIncident"></param>
	/// <param name="reportID"></param>
	/// <param name="dataTime"></param>
	public Report(Complainant newComplainant, Incident newIncident, int reportID){

        this.reportID = reportID;
        this.newComplainant = newComplainant;
        this.newIncident = newIncident;
        //this.dateTime = dateTime;
	}

	/// 
	/// <param name="reportID"></param>
	public string DeleteReport(int reportID){

		return "";
	}
    public void InsertReportData(Report report)
    {
        Complainant.db.Store(report);
        SendReport(report);
        
    }
    public void SendReport(Report report)
    {

        newOfficer.SearchPatrolLocation(report);
    }
    /*public void RecieveIncident(Incident inc, Complainant comp)
    {
        this.newIncident = inc;
        this.newComplainant = 
    }*/
	public ArrayList RetrieveAllReports(){

		return null;
	}

	/// 
	/// <param name="reportID"></param>
	public ArrayList RetrieveReportData(int reportID){

		return null;
	}

	/// 
	/// <param name="reportID"></param>
	public string UpdateReport(int reportID){

		return "";
	}

}//end Report