///////////////////////////////////////////////////////////
//  Shift.cs
//  Implementation of the Class Shift
//  Generated by Enterprise Architect
//  Created on:      04-Apr-2016 6:48:45 PM
//  Original author: ENVY
///////////////////////////////////////////////////////////
using System.Collections;



public class Shift {

	private int duration;
	private int endTime;
	public string shiftDescription;
	private int shiftID;
	private int startTime;

	public Shift(){

	}

	~Shift(){

	}

	public virtual void Dispose(){

	}

	/// 
	/// <param name="shiftID"></param>
	/// <param name="shiftDescription"></param>
	/// <param name="startTime"></param>
	/// <param name="endTime"></param>
	/// <param name="duration"></param>
	public Shift(int shiftID, string shiftDescription, int startTime, int endTime, int duration){
        this.shiftID = shiftID;
        this.shiftDescription = shiftDescription;
        this.startTime = startTime;
        this.endTime = endTime;
        this.duration = duration;
	}

	/// 
	/// <param name="shiftID"></param>
	public string DeleteShiftData(int shiftID){

		return "";
	}

	/// 
	/// <param name="shiftID"></param>
	/// <param name="shiftDescription"></param>
	/// <param name="startTime"></param>
	/// <param name="endTime"></param>
	/// <param name="duration"></param>
	public string InsertShiftData(int shiftID, string shiftDescription, int startTime, int endTime, int duration){

		return "";
	}

	/// 
	/// <param name="shiftID"></param>
	public ArrayList RetrieveShiftData(int shiftID){

		return null;
	}

	/// 
	/// <param name="shiftID"></param>
	public string UpdateShiftData(int shiftID){

		return "";
	}

}//end Shift